eventex/core/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.core.views',url(r'^$', 'homepage', name='homepage'),)

eventex/subscriptions/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url


urlpatterns = patterns('eventex.subscriptions.views',
        url(r'^$', 'subscribe', name='subscribe'),
        url(r'^(\d+)/$', 'detail', name='detail'),
        )

eventex/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^inscricao/', include('eventex.subscriptions.urls', namespace='subscriptions')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'', include('eventex.core.urls', namespace='core')),
    )


from django.conf import settings
urlpatterns += patterns('django.views.static',
    url(r'^static/(?P<path>.*)$', 'serve',
    {'document_root': settings.STATIC_ROOT}),
    )

eventex/core/models.py
from django.db import models

# Create your models here.

eventex/subscriptions/models.py
#coding: utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Subscription(models.Model):
    name = models.CharField(_('nome'), max_length=100)
    cpf = models.CharField(_('CPF'), max_length=11, unique=True)
    email = models.EmailField(_('email'), blank=True)
    phone = models.CharField(_('telefone'), max_length=20, blank=True)
    created_at = models.DateTimeField(_('criado em'), auto_now_add=True)
    paid = models.BooleanField(_('Pago'))

    class Meta:
        ordering = ['created_at']
        verbose_name = _(u'inscrição')
        verbose_name_plural = _(u'inscrições')

    def __unicode__(self):
        return self.name

eventex/subscriptions/forms.py
#coding uft-8
from django.core.validators import EMPTY_VALUES
from django import forms
from django.utils.translation import ugettext as _
from django.core.exceptions import ValidationError
from eventex.subscriptions.models import Subscription


def CPFValidator(value):
    if not value.isdigit():
        raise ValidationError(_(u'CPF deve conter apenas numeros'))
    if len(value) != 11:
        raise ValidationError(_(u'CPF deve ter 11 numeros'))


class PhoneWidget(forms.MultiWidget):

    def __init__(self, attrs=None):
        widgets = (
        forms.TextInput(attrs=attrs),
        forms.TextInput(attrs=attrs))
        super(PhoneWidget, self).__init__(widgets, attrs)

    def decompress(self, value):
        if not value:
            return [None, None]
        return value.split('-')


class PhoneField(forms.MultiValueField):
    widget = PhoneWidget

    def __init__(self, *args, **kwargs):
        fields = (forms.IntegerField(),
        forms.IntegerField())
        super(PhoneField, self).__init__(fields, *args, **kwargs)

    def compress(self, data_list):
        if not data_list:
            return ''
        if data_list[0] in EMPTY_VALUES:
            raise forms.ValidationError(_(u'DDD invalido.'))
        if data_list[1] in EMPTY_VALUES:
            raise forms.ValidationError(_(u'Numero invalido.'))
        return '%s-%s' % tuple(data_list)


class SubscriptionForm(forms.ModelForm):
    phone = PhoneField(label=_('Telefone'), required=False)


    class Meta:

        model = Subscription
        exclude = ('paid',)

    def __init__(self, *args, **kwargs):
        super(SubscriptionForm, self).__init__(*args, **kwargs)
        self.fields['cpf'].validators.append(CPFValidator)

    def clean_name(self):
        name = self.cleaned_data['name']
        words = map(lambda w: w.capitalize(), name.split())
        capitalized_name = ' '.join(words)
        return capitalized_name

    def clean(self):
        super(SubscriptionForm, self).clean()
        if not self.cleaned_data.get('email') and not self.cleaned_data.get('phone'):
            raise ValidationError(_(u'Informe seu e-mail ou telefone'))
        return self.cleaned_data

eventex/core/views.py
# coding: utf-8
from django.shortcuts import render

def homepage(request):
    return render(request,'index.html')

eventex/subscriptions/views.py
# Create your views here.
#coding utf-8
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from eventex.subscriptions.forms import SubscriptionForm
from eventex.subscriptions.models import Subscription
from eventex.subscriptions.models import Subscription

def subscribe(request):
    if request.method == 'POST':
        return create(request)
    else:
        return new(request)

def new(request):
    return render(request,
                  'subscriptions/subscription_form.html',{'form': SubscriptionForm()})

def create(request):
    form = SubscriptionForm(request.POST)
    if not form.is_valid():
        return render(request,
                      'subscriptions/subscription_form.html',{'form': form})
    obj = form.save()
    return HttpResponseRedirect('/inscricao/%d/' % obj.pk)

def detail(request, pk):
    return render(request,
                  'subscriptions/subscription_detail.html')

def detail(request, pk):
    subscription = get_object_or_404(Subscription, pk=pk)
    return render(request,
                  'subscriptions/subscription_detail.html',{'subscription': subscription})

eventex/core/templates/base.html
<!doctype html>
<html>
<head>
  <title>Shadowrun Game Page</title>

  <link type="text/css" href="{{ STATIC_URL }}css/style.css" rel="stylesheet" media="screen" />

</head>
<body>
  <img src="{{ STATIC_URL }}img/logo.png" alt="EventeX" />
    <div id="content">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

eventex/core/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>Welcome to Shadowrun Fan Page</h1>
      <p>Copiado diretamente da página do EventeX, nem me dei ao trabalho de modificar o número de linhas.</p>
        <p><strong><a href="{% url 'subscriptions:subscribe' %}">Coloque seu nome na lista dos Fans</a></strong></p>
      <p>Se você gostava do jogo do SNES, deve olhar para o novo jogo jogo Shadowrun Returns:</p>
      <p><strong><a href ="http://store.steampowered.com/app/234650/?snr=1_7_15__13">Shadowrun Returns</a></strong></p>
      <p>Para dúvidas, entre em contato com os desenvolvedores <a href="mailto:info@hbs-studios.com">info@hbs-studios.com</a></p>
{% endblock content %}

eventex/subscriptions/templates/subscriptions/subscription_detail.html
{% extends 'base.html' %}
{% block content %}
<p>Parabéns {{ subscription.name }},</p>
<p>sua inscrição foi realizada em
{{ subscription.created_at|date:"d/m/Y" }}.
</p>
<p>Em breve, entraremos em contato pelo
{% if subscription.phone %}
telefone {{ subscription.phone }}
{% else %}
e-mail {{ subscription.email }}
{% endif %}
</p>
{% endblock content %}

eventex/subscriptions/templates/subscriptions/subscription_form.html
{% extends 'base.html' %}
{% block content %}
<form action="." method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
<p>
<label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
{{ form.name }}
{{ form.name.errors }}
</p>
<p>
<label for="{{ form.cpf.id_for_label }}">{{ form.cpf.label }}:</label>
{{ form.cpf }}
{{ form.cpf.errors }}
</p>
<p>
<label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
{{ form.email }}
{{ form.email.errors }}
</p>
<p>
<label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}:</label>
{{ form.phone }}
{{ form.phone.errors }}
</p>
<input type="submit" value="Enviar!" class="button" >
</form>
{% endblock content %}